name: Deploy Laravel via SSH (No Test)

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/LVTN_BE

            echo "ğŸ”„ Pull source"
            git pull

            echo "ğŸ“¦ Composer install"
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "âš¡ Optimize Laravel"
            php artisan migrate --force
            php artisan optimize

            echo "ğŸ§¹ Clear cache"
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            echo "ğŸ” Restart queue (náº¿u dÃ¹ng)"
            php artisan queue:restart

            echo "ğŸš€ Done"
